/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classroom.helper;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;

/**
 *
 * @author ianmoore
 */
public class ProChooserSetOps extends javax.swing.JPanel {

    private ClassroomHelper app;
    private ClassS classS;
    private ClassHome homepage;
    private JPanel lastPage;
    private GUIFrame baseFrame;
    private String type;
    private ArrayList<Prompt> prompts;
    private String[] data;
    private DefaultListModel model;
    
    public ProChooserSetOps(ClassroomHelper appl, ClassS cla, ClassHome home, JPanel last, GUIFrame frame, String ty) {
        app = appl;
        classS = cla;
        homepage = home;
        lastPage = last;
        baseFrame = frame;
        type = ty;
        prompts = new ArrayList<Prompt>();
        if(type.equals("SAQ")) {
            for(int i = 0; i < classS.getSAQs().size(); i++) {
               if(!classS.getSAQs().get(i).getIsAns()) {
                   prompts.add(classS.getSAQs().get(i));
               }
            }
        } else {
            for(int i = 0; i < classS.getERQs().size(); i++) {
               if(!classS.getERQs().get(i).getIsAns()) {
                   prompts.add(classS.getERQs().get(i));
               }
            }
        }
        baseFrame.setContentPane(this);
        for(Prompt p: prompts) {
            System.out.println(p.getQue());
        }
        initComponents();
        addProsToList();
        okayB.setEnabled(false);
        jList1.setSelectionModel(new javax.swing.DefaultListSelectionModel() {
            @Override
            public void setSelectionInterval(int index0, int index1) {
                if(super.isSelectedIndex(index0)) {
                    //if the item that was clicked was already selected, deselect it
                    super.removeSelectionInterval(index0, index1);
                } else {
                    //add the item that was clicked to the selection
                    super.addSelectionInterval(index0, index1);
                }
                
                okayB.setEnabled(!super.isSelectionEmpty());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        okayB = new javax.swing.JButton();
        lastPageB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jList1);

        okayB.setText("Okay");
        okayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayBActionPerformed(evt);
            }
        });

        lastPageB.setText("Back");
        lastPageB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastPageBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jLabel1.setText(type + " Prompt Chooser - Set Options");

        jLabel2.setText("Choose which prompts can be randomly selected by clicking on them:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okayB)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastPageB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lastPageB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okayB)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okayBActionPerformed
        ArrayList<Prompt> ops = new ArrayList<Prompt>();
        for(int i = 0; i < jList1.getSelectedIndices().length; i++) {
            ops.add(prompts.get(jList1.getSelectedIndices()[i]));
        }
        
        new DisplayPrompt(app, classS, homepage, baseFrame, classS.rollPro(ops));
    }//GEN-LAST:event_okayBActionPerformed

    private void lastPageBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastPageBActionPerformed
        baseFrame.setContentPane(lastPage);
    }//GEN-LAST:event_lastPageBActionPerformed

    public void addProsToList() {
        model = new DefaultListModel();
        data = new String[prompts.size()];
        
        for(int i = 0; i < prompts.size(); i++) {
            data[i] = prompts.get(i).getQue();
            model.add(i, data[i]);
        }
        
        jList1.setModel(model);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lastPageB;
    private javax.swing.JButton okayB;
    // End of variables declaration//GEN-END:variables
}
