/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classroom.helper;

/**
 *
 * @author ianmoore
 */
public class PromptChooserHome extends javax.swing.JPanel {
    private ClassroomHelper app;
    private ClassS classS;
    private ClassHome homepage;
    private GUIFrame baseFrame;
    
    public PromptChooserHome(ClassroomHelper appl, ClassS cla, ClassHome home, GUIFrame frame, int SAQTally, int ERQTally) {
        app = appl;
        classS = cla;
        homepage = home;
        baseFrame = frame;
        baseFrame.setContentPane(this);
        initComponents();
        if(cla.getLvl().equals("HL")) {
            SAQSelectB.setEnabled(false);
        } else if(SAQTally < 2) {
            SAQSelectB.setEnabled(false);
        }
        if(ERQTally < 2) {
            ERQSelectB.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SAQSelectB = new javax.swing.JButton();
        ERQSelectB = new javax.swing.JButton();
        lastPageB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        SAQSelectB.setText("Select SAQ Prompt");
        SAQSelectB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAQSelectBActionPerformed(evt);
            }
        });

        ERQSelectB.setText("Select ERQ Prompt");
        ERQSelectB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERQSelectBActionPerformed(evt);
            }
        });

        lastPageB.setText("Back");
        lastPageB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastPageBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jLabel1.setText("Prompt Chooser Homepage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ERQSelectB)
                            .addComponent(SAQSelectB))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                        .addComponent(lastPageB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lastPageB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)))
                .addGap(115, 115, 115)
                .addComponent(SAQSelectB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ERQSelectB)
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SAQSelectBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAQSelectBActionPerformed
        new ProChooserSetOps(app, classS, homepage, this, baseFrame, "SAQ");
    }//GEN-LAST:event_SAQSelectBActionPerformed

    private void ERQSelectBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERQSelectBActionPerformed
        new ProChooserSetOps(app, classS, homepage, this, baseFrame, "ERQ");
    }//GEN-LAST:event_ERQSelectBActionPerformed

    private void lastPageBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastPageBActionPerformed
        baseFrame.setContentPane(homepage);
    }//GEN-LAST:event_lastPageBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ERQSelectB;
    private javax.swing.JButton SAQSelectB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lastPageB;
    // End of variables declaration//GEN-END:variables
}
