/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package classroom.helper;

import classroom.helper.GruSorter.IntFormatter;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author ianmoore
 */
public class SortStusPerGru extends javax.swing.JPanel {

    private ClassroomHelper app;
    private ClassS classS;
    private ClassHome homepage;
    private JPanel lastPage;
    private GUIFrame baseFrame;
    private KeyAdapter keyPressEvtLi;
    private GruSorter.IntFormatter intFormatter;
    
    public SortStusPerGru(ClassroomHelper appl, ClassS cla, ClassHome home, JPanel last, GUIFrame frame) {
        app = appl;
        classS = cla;
        homepage = home;
        lastPage = last;
        baseFrame = frame;
        baseFrame.setContentPane(this);
        initComponents();
        generateGrusB.setEnabled(false);
        numEntryF.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                warn();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                warn();
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
                if(!numEntryF.getText().equals("")) {
                    if(Integer.parseInt(numEntryF.getText()) == 0 || Integer.parseInt(numEntryF.getText()) > cla.getPresStus().size()){
                        //System.out.println("error");
                        intFormatter.setInvalidInput();
                        generateGrusB.setEnabled(false);
                    } else {
                        generateGrusB.setEnabled(true);
                    }
                } else {
                    generateGrusB.setEnabled(false);
                }
            }
          });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numEntryF = new javax.swing.JFormattedTextField(intFormatter = new IntFormatter());
        jLabel3 = new javax.swing.JLabel();
        generateGrusB = new javax.swing.JButton();
        lastPageB = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jLabel1.setText("Create New Groups - Set Students Per Group");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("<html>Groups will be generated using the number of student per group specified below. To generate groups </br>based on the the total number of groups needed, return to the previous page.</html>");

        numEntryF.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        numEntryF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numEntryFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numEntryFFocusLost(evt);
            }
        });

        jLabel3.setText("Students per group:");

        generateGrusB.setText("Continue to group generation");
        generateGrusB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateGrusBActionPerformed(evt);
            }
        });

        lastPageB.setText("Back");
        lastPageB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastPageBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(numEntryF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateGrusB))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lastPageB))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lastPageB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numEntryF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(generateGrusB)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numEntryFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numEntryFFocusGained
        numEntryF.addKeyListener(keyPressEvtLi = new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent ev) {
                if(Character.isDigit(ev.getKeyChar()) || ev.getKeyChar() == KeyEvent.VK_BACK_SPACE) {
                    //System.out.println(ev.getKeyChar());
                    if(numEntryF.getText().length() != 0) {
                        if(numEntryF.getText().charAt(0) == '0') {
                            //System.out.println("triggered");
                            numEntryF.setValue("");
                        } else if(Integer.parseInt(numEntryF.getText()) > classS.getPresStus().size()) {
                            ev.consume();
                        }
                    }
                    //setStusPerGruB.setEnabled(numEntryF.getValue().equals(""));
                    //useNoOfGrusB.setEnabled(!numEntryF.getValue().equals(""));
                } else {
                    //System.out.println("done");
                    ev.consume();
                }

            }
        });
    }//GEN-LAST:event_numEntryFFocusGained

    private void numEntryFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numEntryFFocusLost
        numEntryF.removeKeyListener(keyPressEvtLi);
        if(evt.getOppositeComponent() == generateGrusB) {
            generateGrusB.doClick();
        }
    }//GEN-LAST:event_numEntryFFocusLost

    private void generateGrusBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateGrusBActionPerformed
        classS.createNewGrus(true, Integer.parseInt(numEntryF.getText()));
        new ViewAndEditGrus(app, classS, homepage, this, baseFrame, false);
    }//GEN-LAST:event_generateGrusBActionPerformed

    private void lastPageBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastPageBActionPerformed
        baseFrame.setContentPane(lastPage);
    }//GEN-LAST:event_lastPageBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateGrusB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lastPageB;
    private javax.swing.JFormattedTextField numEntryF;
    // End of variables declaration//GEN-END:variables

}
