/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classroom.helper;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author ianmoore
 */
public class StartPage extends javax.swing.JPanel {

    /**
     * Creates new form StartPage
     */
    private ClassroomHelper app;
    private GUIFrame baseFrame;
    
    public StartPage(ClassroomHelper appl, GUIFrame frame) {
        app = appl;
        baseFrame = frame;
        baseFrame.setEnabled(true);
        baseFrame.setVisible(true);
        this.setVisible(true);
        initComponents();
        if(app.getSxnNames().size() == 0) {
            /*createSxnB.setVisible(true);
            createSxnB.setEnabled(true);
            manSxnDataB.setVisible(false);
            manSxnDataB.setEnabled(false);
            startClassB.setVisible(false);
            startClassB.setEnabled(false);
            manProsB.setVisible(false);
            manProsB.setEnabled(false);*/
            setFirstStartup(true);
        }
            //start class button is shown
            //manage sections button is shown
            //when manage sections button is clicked, a new jpanel is shown with buttons to create a section, delete a section and edit a section
            //manage prompts button is shown
        
    }
    
    private void setFirstStartup(boolean first) {
        createSxnB.setVisible(first);
        createSxnB.setEnabled(first);
        manSxnDataB.setVisible(!first);
        manSxnDataB.setEnabled(!first);
        startClassB.setVisible(!first);
        startClassB.setEnabled(!first);
        manProsB.setVisible(!first);
        manProsB.setEnabled(!first);
        if(first) {
            jLabel2.setText("Welcome to the ClassroomHelper app. Please create a section to continue.");
        } else {
            jLabel2.setText("Select a page to continue to:");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createSxnB = new java.awt.Button();
        startClassB = new javax.swing.JButton();
        manSxnDataB = new javax.swing.JButton();
        manProsB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        createSxnB.setEnabled(false);
        createSxnB.setLabel("Create a Section");
        createSxnB.setVisible(false);
        createSxnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSxnBActionPerformed(evt);
            }
        });

        startClassB.setText("Start Class");
        startClassB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startClassBActionPerformed(evt);
            }
        });

        manSxnDataB.setText("Manage Sections");
        manSxnDataB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manSxnDataBActionPerformed(evt);
            }
        });

        manProsB.setText("Manage Prompts");
        manProsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manProsBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jLabel1.setText("Start Page");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Select a page to continue to:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(manProsB)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(startClassB)
                                    .addComponent(createSxnB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(305, 305, 305)
                                .addComponent(manSxnDataB))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(startClassB)
                .addGap(2, 2, 2)
                .addComponent(manSxnDataB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manProsB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createSxnB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createSxnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSxnBActionPerformed
        //System.out.println(evt.getSource());
        //StartPage sta = this;
        //createSxnB.setVisible(false);
        System.out.println("this comp: " + this);
        System.out.println("button parent: " + createSxnB.getParent());

        ManageStuData manStus = new ManageStuData(app, this, baseFrame, true);
        setFirstStartup(false);
        //baseFrame.setContentPane(manStus);
        //manStus.setVisible(true);
        /*this.add(new ManageStuData(app, sta, true));
        this.pack();
        this.setVisible(true);
        //this.setEnabled(false);*/
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("here");
                new ManageStuData(app, sta, true).setVisible(true);
                //System.out.println("null?: " + manStuData != null);
                //if(manStuData != null) {
                    //manStuData.setVisible(true);
                    //}
            }
        });*/
    }//GEN-LAST:event_createSxnBActionPerformed

    private void manSxnDataBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manSxnDataBActionPerformed
        new ManageSxnData(app, this, baseFrame);
    }//GEN-LAST:event_manSxnDataBActionPerformed

    private void startClassBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startClassBActionPerformed
        ClassHome home;
        String sxnStr = (String) javax.swing.JOptionPane.showInputDialog(null, "Choose a section: ", "Start a Class - Section Selection Popup", JOptionPane.PLAIN_MESSAGE, null, app.getSxnNames().toArray(), app.getSxnNames().get(0));
        if(sxnStr != null) {
            String lvlStr = "SL";
            int index = 0;
            for(int i = 0; i < app.getSxnNames().size(); i++) {
                if(app.getSxnNames().get(i).equals(sxnStr)) {
                    if(app.getSxns().size() == 0) {
                        app.loadStus(app.getSxnPaths().get(i));
                    } else {
                        for(int j = 0; j < app.getSxns().size(); j++) {
                            if(app.getSxnNames().get(i).equals(app.getSxns().get(j).getName())) {
                                app.setCurSxn(app.getSxns().get(j));
                                app.setSxnMems(app.getSxns().get(j).getStus());
                            } else if(j == app.getSxns().size() - 1) {
                                app.loadStus(app.getSxnPaths().get(i));
                            }
                        }
                    }
                    index = i;
                }
            }
            
            for(int s = 0; s < app.getSxnMems().size(); s++) {
                if(app.getSxnMems().get(s).getIsHL()) {
                    lvlStr = (String) javax.swing.JOptionPane.showInputDialog(null, "Choose a level: ", "Start a Class - Level Selection Popup", JOptionPane.PLAIN_MESSAGE, null, new String[]{"Mixed (SL/HL)", "HL Only"}, "Mixed (SL/HL)");
                    break;
                }
            }
            
            if(lvlStr != null) {
                System.out.println("SxnStr: " + sxnStr + ", lvlStr: " + lvlStr);
                if(lvlStr.equals("Mixed (SL/HL)")) {
                    lvlStr = "SL";
                } else if(lvlStr.equals("HL Only")) {
                    lvlStr = "HL";
                }
                //System.out.println("sections size: " + app.getSxns().size());
                if(app.startClass(index, lvlStr)) {
                    home = new ClassHome(app, app.getCurSxn().loadClass(lvlStr), this, baseFrame);
                }
            }
        }        
    }//GEN-LAST:event_startClassBActionPerformed

    private void manProsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manProsBActionPerformed
        new ManageProData(app, this, baseFrame, false);
    }//GEN-LAST:event_manProsBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button createSxnB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manProsB;
    private javax.swing.JButton manSxnDataB;
    private javax.swing.JButton startClassB;
    // End of variables declaration//GEN-END:variables
}
